version: '3.7'

services:
  postgres:
    image: postgres:12
    container_name: coders-board-integration-test-postgres
    restart: always
    ports:
      - 5002:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: coders-board
    networks:
      - coders-board-integration-test-network

  eventstore:
    container_name: coders-board-integration-test-eventstore
    image: eventstore/eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_INT_TCP_PORT=1112
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INT_HTTP_PORT=2112
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_DISABLE_HTTP_CACHING=false
    ports:
      - "1112:1112"
      - "1113:1113"
      - "2112:2112"
      - "2113:2113"
    networks:
      - coders-board-integration-test-network

networks:
  coders-board-integration-test-network:
    name: coders-board-integration-test-network
