version: '3.7'

services:
  coders-board:
    build:
      args:
        NODE_ENV: development
        IMAGE_BASE_DEV: node:alpine
        IMAGE_BASE_PROD: node:alpine
      context: .
      target: development

    container_name: coders-board-nestjs
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      EVENTSOURCING_MODE: in-memory
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      EVENTSTORE_USERNAME: admin
      EVENTSTORE_PASSWORD: changeit
      EVENTSTORE_URL: http://eventstore:2113
    command:
      - start:debug
    networks:
      - coders-board-network

  postgres:
    image: postgres:12
    container_name: coders-board-postgres
    restart: always
    ports:
      - 5002:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: coders-board
    networks:
      - coders-board-network
    #volumes:
    # - ../pgdata:/var/lib/postgresql/data #keep data outside container

  eventstore:
    container_name: coders-board-eventstore.
    image: eventstore/eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_INT_TCP_PORT=1112
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INT_HTTP_PORT=2112
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
    ports:
      - "1112:1112"
      - "1113:1113"
      - "2112:2112"
      - "2113:2113"
    networks:
      - coders-board-network

networks:
  coders-board-network:
    name: coders-board-network
