name: Publish CodersBoard backend Docker image
on:
  push:
    branches:
      - docker
defaults:
  run:
    working-directory: backend/
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: CodersCrew/coders-board-v2/codersboard-backend-draft
        #  tag_with_ref: true TODO: When config will be done
          tags: draft
          tag_with_sha: true
          push: true
          target: productio